export const Plants = 
    [
            {
                "name": "Monstera Deliciosa",
                "type": "Tropical",
                "humidity": true,
                "hardy": false,
                "light": "bright indirect light", 
                "photo": "./assets/images/monstera-deliciosa.jpg",
                "water": true,
            },
            {
                "name": "Monstera Adansonii",
                "type": "Tropical",
                "humidity": true,
                "hardy": false,
                "light": "bright indirect light",
                "photo": "./assets/images/monstera-adansonii.jpg",
                "water": true,
            },
            {
                "name": "Rubber Plant",
                "type": "Tropical",
                "humidity": true,
                "hardy": true,
                "light": "medium to bright indirect light",
                "photo": "./assets/images/rubber-plant.jpg",
                "water": true,
            },
            {
                "name": "String of Pearls",
                "type": "Succulent",
                "humidity": false,
                "hardy": true,
                "light": "bright indirect light",
                "photo": "./assets/images/string-of-pearls.jpg",
                "water": false,
            },
            {
                "name": "Aloe Vera",
                "type": "Succulent",
                "humidity": false,
                "hardy": true,
                "light": "bright indirect light",
                "photo": "./assets/images/aloe-vera.jpg",
                "water": false,
            },
            {
                "name": "Fittonia",
                "type": "Shade Plant",
                "humidity": true,
                "hardy": true,
                "light": "low to medium light",
                "photo": "./assets/images/fittonia.jpg",
                "water": true,
            },
            {
                "name": "Pothos",
                "type": "Shade Plant",
                "humidity": false,
                "hardy": true,
                "light": "low to medium light",
                "photo": "./assets/images/pothos.jpg",
                "water": false,
            },
            {
                "name": "Fiddle Leaf Fig",
                "type": "Ficus Tree",
                "humidity": true,
                "hardy": false,
                "light": "bright indirect light",
                "photo": "./assets/images/fiddle-leaf-fig.jpeg",
                "water": true,
            },
            {
                "name": "Prayer Plant",
                "type": "Shade Plant",
                "humidity": true,
                "hardy": false,
                "light": "low to medium light",
                "photo": "./assets/images/prayer-plant.jpeg",
                "water": true,
            },
            {
                "name": "Kalanchoe",
                "type": "Succulent",
                "humidity": false,
                "hardy": true,
                "light": "bright indirect light",
                "photo": "./assets/images/kalanchoe.jpg",
                "water": false,
            },
            {
                "name": "Hoya Heart",
                "type": "Succulent",
                "humidity": false,
                "hardy": true,
                "light": "bright indirect light",
                "photo": "./assets/images/hoya-heart.jpg",
                "water": false,
            },
            {
                "name": "Peacock Plant",
                "type": "Tropical",
                "humidity": true,
                "hardy": false,
                "light": "low to medium light",
                "photo": "./assets/images/peacock-plant.jpg",
                "water": true,
            },
            {
                "name": "Snake Plant",
                "type": "Succulent",
                "humidity": false,
                "hardy": true,
                "light": "low to medium light",
                "photo": "./assets/images/snake-plant.jpg",
                "water": false,
            },
            {
                "name": "Chinese Money Plant",
                "type": "Succulent",
                "humidity": false,
                "hardy": true,
                "light": "medium light",
                "photo": "./assets/images/chinese-money-plant.jpg",
                "water": false,
            },
            {
                "name": "Spearpoint Ivy",
                "type": "Shade Plant",
                "humidity": false,
                "hardy": true,
                "light": "medium light",
                "photo": "./assets/images/spearpoint-ivy.jpg",
                "water": true,
            },
            {     
                "name": "Orchid",
                "type": "Tropical",
                "humidity": true,
                "hardy": false,
                "light": "bright indirect light",
                "photo": "./assets/images/orchid.jpeg",
                "water": true,
            },
            {
                "name": "Jade Plant",
                "type": "Succulent",
                "humidity": false,
                "hardy": true,
                "light": "bright indirect light",
                "photo": "./assets/images/jade-plant.jpg",
                "water": false,
            },
            {
                "name": "Umbrella Tree",
                "type": "Tropical",
                "humidity": true,
                "hardy": true,
                "light": "bright indirect light",
                "photo": "./assets/images/umbrella-tree.jpg",
                "water": true,
            },
            {
                "name": "Bromeliad",
                "type": "Tropical Shade Plant",
                "humidity": false,
                "hardy": true,
                "light": "low to medium light",
                "photo": "./assets/images/bromeliad.jpg",
                "water": false,
            },
            {
                "name": "Oxalis",
                "type": "Shade Plant",
                "humidity": false,
                "hardy": true,
                "light": "low to medium light",
                "photo": "./assets/images/oxalis.jpg",
                "water": true,
            },
            {
                "name": "ZZ Plant",
                "type": "Shade Plant",
                "humidity": false,
                "hardy": true,
                "light": "low to medium light",
                "photo": "./assets/images/zz-plant.jpg",
                "water": false,
            }



            
            
        
    ]
